
 profiles:
    active: dev
  cloud:
    config:
      fail-fast: true
      profile: ${spring.profiles.active}
      label: ${spring.profiles.active}
my:
  greeting: welcome to GL
  list:
    values: core,spring,jpa
  age: 20